####################################################################################################
#                ██████          █████                              █████    █████                 #
#               ███░░███        ░░███                              ░░███    ░░███                  #
#              ░███ ░░░   █████  ░███████      ██    ██     █████  ███████   ░███ █████            #
#             ███████    ███░░   ░███░░███    ░░    ░░     ███░░  ░░░███░    ░███░░███             #
#            ░░░███░    ░░█████  ░███ ░███                ░░█████   ░███     ░██████░              #
#              ░███      ░░░░███ ░███ ░███                 ░░░░███  ░███ ███ ░███░░███             #
#              █████     ██████  ████ █████    ██    ██    ██████   ░░█████  ████ █████            #
#            ░░░░░     ░░░░░░  ░░░░ ░░░░░    ░░    ░░    ░░░░░░     ░░░░░  ░░░░ ░░░░░              #
#                                                                                                  #
#           fantastic  spatial  holophonic                software    tool    kit                  #
#                                                                                                  #
#                                   copyright (c) fabian hummel                                    #
#                                      www.github.com/fshstk                                       #
#                                          www.fshstk.com                                          #
#                                                                                                  #
#        this file is part of the fantastic spatial holophonic software toolkit (fsh::stk)         #
# fsh::stk is free software: it is provided under the terms of the gnu general public license v3.0 #
#                                   www.gnu.org/licenses/gpl-3.0                                   #
####################################################################################################
# Some parts of this script are based on www.github.com/maxwellpollack/juce-plugin-ci              #
####################################################################################################

name: build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        config:
          - { name: "macOS", os: macos-latest }
          - { name: "Windows", os: windows-latest }
          - { name: "Linux", os: ubuntu-latest }
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - if: ${{ runner.os == 'Linux' }}
        name: Install JUCE dependencies (Linux only)
        id: juce_dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            freeglut3-dev \
            g++ \
            libasound2-dev \
            libcurl4-openssl-dev \
            libfreetype6-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-37 \
            libwebkit2gtk-4.0-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxrandr-dev \
            mesa-common-dev

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B build

      - name: Build
        working-directory: build
        run: cmake --build . --config ${{ env.BUILD_TYPE }}
