####################################################################################################
#                ██████          █████                              █████    █████                 #
#               ███░░███        ░░███                              ░░███    ░░███                  #
#              ░███ ░░░   █████  ░███████      ██    ██     █████  ███████   ░███ █████            #
#             ███████    ███░░   ░███░░███    ░░    ░░     ███░░  ░░░███░    ░███░░███             #
#            ░░░███░    ░░█████  ░███ ░███                ░░█████   ░███     ░██████░              #
#              ░███      ░░░░███ ░███ ░███                 ░░░░███  ░███ ███ ░███░░███             #
#              █████     ██████  ████ █████    ██    ██    ██████   ░░█████  ████ █████            #
#            ░░░░░     ░░░░░░  ░░░░ ░░░░░    ░░    ░░    ░░░░░░     ░░░░░  ░░░░ ░░░░░              #
#                                                                                                  #
#           fantastic  spatial  holophonic               synthesis    tool    kit                  #
#                                                                                                  #
#                                   copyright (c) fabian hummel                                    #
#                                      www.github.com/fshstk                                       #
#                                          www.fshstk.com                                          #
#                                                                                                  #
#        this file is part of the fantastic spatial holophonic synthesis toolkit (fsh::stk)         #
# fsh::stk is free software: it is provided under the terms of the gnu general public license v3.0 #
#                                   www.gnu.org/licenses/gpl-3.0                                   #
####################################################################################################
# Some parts of this script are based on www.github.com/maxwellpollack/juce-plugin-ci              #
####################################################################################################

name: sync docs

on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  docs:
    name: Upload documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JUCE dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            freeglut3-dev \
            g++ \
            libasound2-dev \
            libcurl4-openssl-dev \
            libfreetype6-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-37 \
            libwebkit2gtk-4.0-dev \
            libx11-dev \
            libxcomposite-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxrandr-dev \
            mesa-common-dev \
            rsync \
            sshpass \
            wget \
            graphviz
          wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
          tar -xzf doxygen-1.10.0.linux.bin.tar.gz

      # Configure step is needed for custom CSS:
      - name: Install Doxygen
        run: |
          FILE=doxygen-1.10.0.linux.bin.tar.gz
          wget https://www.doxygen.nl/files/${FILE}
          CALCULATED_SHA256=$(sha256sum ${FILE} | awk '{print $1}')
          EXPECTED_SHA256="dcfc9aa4cc05aef1f0407817612ad9e9201d9bf2ce67cecf95a024bba7d39747"
          if [ "$CALCULATED_SHA256" != "$EXPECTED_SHA256" ]; then
            echo "ERROR: SHA256 mismatch for Doxygen:"
            echo "EXPECTED: ${EXPECTED_SHA256}"
            echo "ACTUAL:   ${CALCULATED_SHA256}"
            exit 1
          fi
          tar -xzf ${FILE}

      # Configure step is needed for custom CSS:
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -B build

      # Doxygen < 1.10 (as installed by apt) will throw an error when docstring
      # comments are formatted without "*" at the beginning of each line:
      - name: Generate docs
        run: ./doxygen-1.10.0/bin/doxygen

      - name: Sync docs directory
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_ID }}" >> ~/.ssh/known_hosts
          sshpass -p ${{ env.SSH_PASS }} rsync -avz --delete docs/html/ ${{ env.SSH_USER }}@docs.fshstk.com:~/docs.fshstk.com
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_ID: docs.fshstk.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICoRSttmGhja67iWGqH/tNcK7JydvAX4ljVWWJqFb9IJ
